# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(default=0)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.Beacon')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=32)),
                ('beacon_total_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.Time'),
        ),
    ]
