# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='uuid',
            field=models.UUIDField(default='22f32866-be04-11e7-abc4-cec278b6b50a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signal',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='beacon.Time'),
        ),
    ]
