# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_auto_20171106_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='signal',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
